# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
#logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

engines:
  logger:
    LogReport:
      app_name: Lenio
      dispatchers:
        default:
          type: SYSLOG
          identity: GADS
          facility: local0
          flags: "pid ndelay nowait"
          mode: VERBOSE
